### ISSUE TITLE
png报错

### ISSUE THREAD

**Issue by ybwang119** [YuxueYang1204/Literature_Reading_Report_Template#1]
图像采用png会无法编译
添加\usepackage{graphicx}会导致编译失败
`<to be read again> 
                   }
l.30     \includegraphics{main/images/pic1.png}
                                               
The requested image couldn't be read because
it was not a recognized image format.`

**Comment by YuxueYang1204** [comment]
@ybwang119  I have updated `main.tex`, which has been verified to work properly.
