### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by 0x3f3f3f3fun** [YuxueYang1204/Literature_Reading_Report_Template#2]
Thanks for the template :D. I have found a typo in main.tex:
https://github.com/YuxueYang1204/Literature_Reading_Report_Template/blob/e4dbdbee8066d9dd4ed10ebbaa273576ccf150c7/main.tex#L27
`fig/UCAS.png` should be `figures/UCAS.png`.

**Comment by YuxueYang1204** [comment]
Thanks for your attention! I have fixed the bug!
